name: Test flow
on:
  push:
    paths:
      - 'packages/test-package/**'
    branches:
      - '[0-9]+.x'
      - 'main'
      - 'master'
      - 'next'
      - 'beta'
      - 'alpha'
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/test-package
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run build script
        run: npm run build
      - name: Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
